### PR TITLE
Landing Page

### LINKED ISSUE #1: Basic landing page
We need a landing page! It just needs to be a flat page. For the time being, it should just have a title and links to the three other pages (this can be stubbed out for now).

Feel free to work with someone on this!

### PR DESCRIPTION
**Pull request by J3RN**
My landing page (as well as some other fundamental) changes.
Closes #1

### CODE REVIEW

**Comment by J3RN** [comment]
The latest version is attached. It looks a little unbalanced, so I might go back to the drawing board with this design a little bit. What does anyone else think? @afuhrtrumpet @Alexanau 
screen shot 2014-10-23 at 12 49 04 am

(I'm hovering over "About", you just can't see it)

**Comment by J3RN** [comment]
I just spent the last half hour _not_ sleeping, and fighting CSS instead. What do you think about this, for comparison?
screen shot 2014-10-23 at 1 32 31 am

**Comment by afuhrtrumpet** [comment]
Looks awesome, and the C is almost a circle! I like the second one better.

**Comment by J3RN** [comment]
Before I merge this, I think I'll actually have to change the font. Helvetica is super proprietary, and not everyone has it, and I can't do an `@font-face` with it.

@afuhrtrumpet I agree, the second one looks better. It sort of abandons the logo concept, but it's just so much more balanced.

**Comment by J3RN** [comment]
Safari still uses vendor prefixes **this is 2014**. Fix on the way.

**Pull request merged**
